### ISSUE TITLE
Troubles with the normalization notebooks

### ISSUE THREAD

**Issue by anderskaestner** [neutronimaging/python_notebooks#9]
The NeuNorm module is missing when I try to start the normalization notebooks. I also can't find it among the files in __code.

**Comment by JeanBilheux** [comment]
the NeuNorm library is an exterior library I wrote but requested by most of the notebook. I'm going to fix the setup.py file to make sure this one is added automatically when installing the library

**Comment by JeanBilheux** [comment]
The instruction in the README should have taken care of this.
